[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit-extras>=0.5.5",
    "streamlit>=1.43.0",
    "pandas>=2.2.3",
    "twilio>=9.4.6",
]
